# Generated by Django 4.2.7 on 2025-11-10 16:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("monitoring", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Alert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="fecha de actualización"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="activo")),
                ("title", models.CharField(max_length=255, verbose_name="título")),
                ("message", models.TextField(verbose_name="mensaje")),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("low", "Baja"),
                            ("medium", "Media"),
                            ("high", "Alta"),
                            ("critical", "Crítica"),
                        ],
                        max_length=20,
                        verbose_name="severidad",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendiente"),
                            ("sent", "Enviado"),
                            ("failed", "Fallido"),
                            ("acknowledged", "Reconocido"),
                            ("resolved", "Resuelto"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="estado",
                    ),
                ),
                (
                    "alert_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Datos adicionales de contexto",
                        verbose_name="datos de alerta",
                    ),
                ),
                (
                    "sent_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="enviado en"
                    ),
                ),
                (
                    "delivery_details",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Información sobre el envío por cada canal",
                        verbose_name="detalles de entrega",
                    ),
                ),
                (
                    "acknowledged_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="reconocido en"
                    ),
                ),
                (
                    "resolved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="resuelto en"
                    ),
                ),
                (
                    "resolution_notes",
                    models.TextField(blank=True, verbose_name="notas de resolución"),
                ),
                (
                    "acknowledged_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="acknowledged_alerts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="reconocido por",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="creado por",
                    ),
                ),
                (
                    "detection",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alerts",
                        to="monitoring.detection",
                        verbose_name="detección",
                    ),
                ),
                (
                    "monitor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alerts",
                        to="monitoring.monitor",
                        verbose_name="monitor",
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resolved_alerts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="resuelto por",
                    ),
                ),
            ],
            options={
                "verbose_name": "alerta",
                "verbose_name_plural": "alertas",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AlertChannel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="fecha de actualización"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="activo")),
                ("name", models.CharField(max_length=255, verbose_name="nombre")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="descripción"),
                ),
                (
                    "channel_type",
                    models.CharField(
                        choices=[
                            ("email", "Email"),
                            ("sms", "SMS"),
                            ("webhook", "Webhook"),
                            ("slack", "Slack"),
                            ("telegram", "Telegram"),
                            ("push", "Push Notification"),
                            ("in_app", "In-App"),
                        ],
                        max_length=20,
                        verbose_name="tipo de canal",
                    ),
                ),
                (
                    "configuration",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Configuración específica del canal (URL, credenciales, etc.)",
                        verbose_name="configuración",
                    ),
                ),
                (
                    "is_enabled",
                    models.BooleanField(default=True, verbose_name="habilitado"),
                ),
                (
                    "last_used",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="último uso"
                    ),
                ),
                (
                    "total_sent",
                    models.IntegerField(default=0, verbose_name="total enviados"),
                ),
                (
                    "total_failed",
                    models.IntegerField(default=0, verbose_name="total fallidos"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="creado por",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="actualizado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "canal de alerta",
                "verbose_name_plural": "canales de alerta",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="AlertTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="fecha de actualización"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="activo")),
                (
                    "name",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="nombre"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="descripción"),
                ),
                (
                    "subject_template",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="plantilla de asunto"
                    ),
                ),
                ("body_template", models.TextField(verbose_name="plantilla de cuerpo")),
                (
                    "variables",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Lista de variables que se pueden usar en la plantilla",
                        verbose_name="variables disponibles",
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(default=False, verbose_name="es por defecto"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="creado por",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="actualizado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "plantilla de alerta",
                "verbose_name_plural": "plantillas de alertas",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="AlertRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="fecha de actualización"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="activo")),
                ("name", models.CharField(max_length=255, verbose_name="nombre")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="descripción"),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("low", "Baja"),
                            ("medium", "Media"),
                            ("high", "Alta"),
                            ("critical", "Crítica"),
                        ],
                        default="medium",
                        help_text="Severidad mínima para activar la alerta",
                        max_length=20,
                        verbose_name="severidad mínima",
                    ),
                ),
                (
                    "trigger_type",
                    models.CharField(
                        choices=[
                            ("detection", "Detección"),
                            ("threshold", "Umbral"),
                            ("schedule", "Programado"),
                            ("custom", "Personalizado"),
                        ],
                        default="detection",
                        max_length=20,
                        verbose_name="tipo de activación",
                    ),
                ),
                (
                    "conditions",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Condiciones para activar la alerta",
                        verbose_name="condiciones",
                    ),
                ),
                (
                    "message_template",
                    models.TextField(
                        blank=True,
                        help_text="Plantilla del mensaje de alerta (soporta variables)",
                        verbose_name="plantilla de mensaje",
                    ),
                ),
                (
                    "throttle_minutes",
                    models.IntegerField(
                        default=0,
                        help_text="Minutos a esperar antes de enviar otra alerta similar (0 = sin límite)",
                        verbose_name="minutos de espera",
                    ),
                ),
                (
                    "is_enabled",
                    models.BooleanField(default=True, verbose_name="habilitado"),
                ),
                (
                    "trigger_count",
                    models.IntegerField(
                        default=0, verbose_name="número de activaciones"
                    ),
                ),
                (
                    "last_triggered",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="última activación"
                    ),
                ),
                (
                    "channels",
                    models.ManyToManyField(
                        related_name="alert_rules",
                        to="alerts.alertchannel",
                        verbose_name="canales",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="creado por",
                    ),
                ),
                (
                    "monitors",
                    models.ManyToManyField(
                        blank=True,
                        related_name="alert_rules",
                        to="monitoring.monitor",
                        verbose_name="monitores",
                    ),
                ),
                (
                    "projects",
                    models.ManyToManyField(
                        blank=True,
                        related_name="alert_rules",
                        to="monitoring.monitoringproject",
                        verbose_name="proyectos",
                    ),
                ),
                (
                    "recipients",
                    models.ManyToManyField(
                        blank=True,
                        related_name="alert_rules",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="destinatarios",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="actualizado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "regla de alerta",
                "verbose_name_plural": "reglas de alerta",
                "ordering": ["-severity", "name"],
            },
        ),
        migrations.CreateModel(
            name="AlertLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("success", "Exitoso"),
                            ("failed", "Fallido"),
                            ("pending", "Pendiente"),
                            ("retry", "Reintentando"),
                        ],
                        max_length=20,
                        verbose_name="estado",
                    ),
                ),
                (
                    "sent_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="enviado en"),
                ),
                (
                    "response",
                    models.TextField(
                        blank=True,
                        help_text="Respuesta del servicio de entrega",
                        verbose_name="respuesta",
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="mensaje de error"),
                ),
                (
                    "retry_count",
                    models.IntegerField(default=0, verbose_name="intentos"),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="metadatos"
                    ),
                ),
                (
                    "alert",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="alerts.alert",
                        verbose_name="alerta",
                    ),
                ),
                (
                    "channel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="alerts.alertchannel",
                        verbose_name="canal",
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alert_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="destinatario",
                    ),
                ),
            ],
            options={
                "verbose_name": "log de alerta",
                "verbose_name_plural": "logs de alertas",
                "ordering": ["-sent_at"],
            },
        ),
        migrations.AddField(
            model_name="alert",
            name="rule",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="alerts",
                to="alerts.alertrule",
                verbose_name="regla",
            ),
        ),
        migrations.AddField(
            model_name="alert",
            name="updated_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
                verbose_name="actualizado por",
            ),
        ),
        migrations.CreateModel(
            name="AlertSubscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="fecha de actualización"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="activo")),
                (
                    "min_severity",
                    models.CharField(
                        choices=[
                            ("low", "Baja"),
                            ("medium", "Media"),
                            ("high", "Alta"),
                            ("critical", "Crítica"),
                        ],
                        default="medium",
                        max_length=20,
                        verbose_name="severidad mínima",
                    ),
                ),
                (
                    "quiet_hours_start",
                    models.TimeField(
                        blank=True,
                        help_text="No enviar alertas durante este período",
                        null=True,
                        verbose_name="inicio de horas silenciosas",
                    ),
                ),
                (
                    "quiet_hours_end",
                    models.TimeField(
                        blank=True, null=True, verbose_name="fin de horas silenciosas"
                    ),
                ),
                (
                    "is_enabled",
                    models.BooleanField(default=True, verbose_name="habilitado"),
                ),
                (
                    "channels",
                    models.ManyToManyField(
                        related_name="subscriptions",
                        to="alerts.alertchannel",
                        verbose_name="canales preferidos",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="creado por",
                    ),
                ),
                (
                    "monitors",
                    models.ManyToManyField(
                        blank=True,
                        related_name="subscriptions",
                        to="monitoring.monitor",
                        verbose_name="monitores",
                    ),
                ),
                (
                    "projects",
                    models.ManyToManyField(
                        blank=True,
                        related_name="subscriptions",
                        to="monitoring.monitoringproject",
                        verbose_name="proyectos",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="actualizado por",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alert_subscriptions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "suscripción de alerta",
                "verbose_name_plural": "suscripciones de alertas",
                "ordering": ["user", "-created_at"],
                "unique_together": {("user",)},
            },
        ),
        migrations.AddIndex(
            model_name="alertrule",
            index=models.Index(
                fields=["trigger_type", "is_enabled"],
                name="alerts_aler_trigger_bde435_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="alertrule",
            index=models.Index(
                fields=["severity", "is_enabled"], name="alerts_aler_severit_1100c0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="alertlog",
            index=models.Index(
                fields=["alert", "status"], name="alerts_aler_alert_i_78a279_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="alertlog",
            index=models.Index(
                fields=["channel", "status"], name="alerts_aler_channel_2df019_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="alertlog",
            index=models.Index(
                fields=["sent_at"], name="alerts_aler_sent_at_5d07b5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="alert",
            index=models.Index(
                fields=["rule", "status"], name="alerts_aler_rule_id_b4fe5e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="alert",
            index=models.Index(
                fields=["severity", "status"], name="alerts_aler_severit_12d0e1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="alert",
            index=models.Index(
                fields=["created_at"], name="alerts_aler_created_8af5ce_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="alert",
            index=models.Index(
                fields=["status", "severity"], name="alerts_aler_status_58cd09_idx"
            ),
        ),
    ]
