# Generated by Django 4.2.7 on 2025-11-10 16:32

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DataSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="fecha de actualización"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="activo")),
                (
                    "name",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="nombre"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="descripción"),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("wms", "Web Map Service"),
                            ("wfs", "Web Feature Service"),
                            ("wmts", "Web Map Tile Service"),
                            ("api", "REST API"),
                            ("database", "Base de Datos"),
                            ("file", "Archivo"),
                            ("sentinel", "Sentinel Hub"),
                            ("landsat", "Landsat"),
                            ("custom", "Personalizado"),
                        ],
                        max_length=20,
                        verbose_name="tipo de fuente",
                    ),
                ),
                (
                    "url",
                    models.URLField(blank=True, max_length=500, verbose_name="URL"),
                ),
                (
                    "credentials",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="API keys, tokens, usuario/contraseña encriptados",
                        verbose_name="credenciales",
                    ),
                ),
                (
                    "configuration",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Parámetros adicionales de configuración",
                        verbose_name="configuración",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Activo"),
                            ("inactive", "Inactivo"),
                            ("error", "Error"),
                            ("maintenance", "Mantenimiento"),
                        ],
                        default="active",
                        max_length=20,
                        verbose_name="estado",
                    ),
                ),
                (
                    "refresh_interval",
                    models.IntegerField(
                        default=60,
                        help_text="0 para actualización manual",
                        verbose_name="intervalo de actualización (minutos)",
                    ),
                ),
                (
                    "last_sync",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="última sincronización"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="metadatos"
                    ),
                ),
                (
                    "tags",
                    models.JSONField(
                        blank=True, default=list, verbose_name="etiquetas"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="creado por",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="actualizado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "fuente de datos",
                "verbose_name_plural": "fuentes de datos",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Layer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="fecha de actualización"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="activo")),
                ("name", models.CharField(max_length=255, verbose_name="nombre")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="descripción"),
                ),
                (
                    "layer_type",
                    models.CharField(
                        choices=[
                            ("vector", "Vectorial"),
                            ("raster", "Raster"),
                            ("point_cloud", "Nube de Puntos"),
                            ("tile", "Tiles"),
                        ],
                        max_length=20,
                        verbose_name="tipo de capa",
                    ),
                ),
                (
                    "geometry_type",
                    models.CharField(
                        choices=[
                            ("point", "Punto"),
                            ("linestring", "Línea"),
                            ("polygon", "Polígono"),
                            ("multipoint", "Multipunto"),
                            ("multilinestring", "Multilínea"),
                            ("multipolygon", "Multipolígono"),
                            ("geometrycollection", "Colección"),
                            ("raster", "Raster"),
                        ],
                        max_length=30,
                        verbose_name="tipo de geometría",
                    ),
                ),
                (
                    "srid",
                    models.IntegerField(
                        default=4326,
                        help_text="Sistema de referencia espacial (EPSG)",
                        verbose_name="SRID",
                    ),
                ),
                (
                    "extent",
                    django.contrib.gis.db.models.fields.PolygonField(
                        blank=True,
                        help_text="Bounding box de la capa",
                        null=True,
                        srid=4326,
                        verbose_name="extensión",
                    ),
                ),
                (
                    "style",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Configuración de estilos para visualización",
                        verbose_name="estilo",
                    ),
                ),
                (
                    "properties_schema",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Definición de campos y tipos de datos",
                        verbose_name="esquema de propiedades",
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(default=False, verbose_name="público"),
                ),
                (
                    "is_queryable",
                    models.BooleanField(default=True, verbose_name="consultable"),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="metadatos"
                    ),
                ),
                (
                    "tags",
                    models.JSONField(
                        blank=True, default=list, verbose_name="etiquetas"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="creado por",
                    ),
                ),
                (
                    "data_source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="layers",
                        to="geodata.datasource",
                        verbose_name="fuente de datos",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="actualizado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "capa",
                "verbose_name_plural": "capas",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Feature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="fecha de actualización"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="activo")),
                (
                    "geometry",
                    django.contrib.gis.db.models.fields.GeometryField(
                        srid=4326, verbose_name="geometría"
                    ),
                ),
                (
                    "properties",
                    models.JSONField(
                        default=dict,
                        help_text="Atributos del feature en formato GeoJSON",
                        verbose_name="propiedades",
                    ),
                ),
                (
                    "feature_id",
                    models.CharField(
                        blank=True,
                        help_text="ID externo del feature",
                        max_length=255,
                        verbose_name="ID de feature",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="creado por",
                    ),
                ),
                (
                    "layer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="features",
                        to="geodata.layer",
                        verbose_name="capa",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="actualizado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "feature",
                "verbose_name_plural": "features",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Dataset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="fecha de actualización"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="activo")),
                (
                    "name",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="nombre"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="descripción"),
                ),
                (
                    "is_public",
                    models.BooleanField(default=False, verbose_name="público"),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="metadatos"
                    ),
                ),
                (
                    "tags",
                    models.JSONField(
                        blank=True, default=list, verbose_name="etiquetas"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="creado por",
                    ),
                ),
                (
                    "layers",
                    models.ManyToManyField(
                        blank=True,
                        related_name="datasets",
                        to="geodata.layer",
                        verbose_name="capas",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="actualizado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "dataset",
                "verbose_name_plural": "datasets",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="SyncLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("success", "Exitoso"),
                            ("failed", "Fallido"),
                            ("partial", "Parcial"),
                        ],
                        max_length=20,
                        verbose_name="estado",
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="iniciado en"),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="completado en"
                    ),
                ),
                (
                    "records_processed",
                    models.IntegerField(default=0, verbose_name="registros procesados"),
                ),
                (
                    "records_added",
                    models.IntegerField(default=0, verbose_name="registros añadidos"),
                ),
                (
                    "records_updated",
                    models.IntegerField(
                        default=0, verbose_name="registros actualizados"
                    ),
                ),
                (
                    "records_failed",
                    models.IntegerField(default=0, verbose_name="registros fallidos"),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="mensaje de error"),
                ),
                (
                    "details",
                    models.JSONField(blank=True, default=dict, verbose_name="detalles"),
                ),
                (
                    "data_source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sync_logs",
                        to="geodata.datasource",
                        verbose_name="fuente de datos",
                    ),
                ),
            ],
            options={
                "verbose_name": "log de sincronización",
                "verbose_name_plural": "logs de sincronización",
                "ordering": ["-started_at"],
                "indexes": [
                    models.Index(
                        fields=["data_source", "status"],
                        name="geodata_syn_data_so_54daee_idx",
                    ),
                    models.Index(
                        fields=["started_at"], name="geodata_syn_started_ae8895_idx"
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="layer",
            index=models.Index(
                fields=["layer_type", "is_active"],
                name="geodata_lay_layer_t_3efe50_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="layer",
            index=models.Index(
                fields=["data_source", "is_public"],
                name="geodata_lay_data_so_bb35b8_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="layer",
            unique_together={("data_source", "name")},
        ),
        migrations.AddIndex(
            model_name="feature",
            index=models.Index(
                fields=["layer", "is_active"], name="geodata_fea_layer_i_f6ae3a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="feature",
            index=models.Index(
                fields=["feature_id"], name="geodata_fea_feature_041fbf_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="datasource",
            index=models.Index(
                fields=["source_type", "status"], name="geodata_dat_source__b59f18_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="datasource",
            index=models.Index(
                fields=["created_at"], name="geodata_dat_created_d418b8_idx"
            ),
        ),
    ]
