# Generated by Django 4.2.7 on 2025-11-30 23:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("geodata", "0002_layer_upload_support"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="layer",
            name="geodata_lay_data_so_bb35b8_idx",
        ),
        migrations.AddIndex(
            model_name="layer",
            index=models.Index(
                fields=["is_public"], name="geodata_lay_is_publ_93f0b5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="layer",
            index=models.Index(
                fields=["created_at"], name="geodata_lay_created_393c80_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="layer",
            index=models.Index(fields=["name"], name="geodata_lay_name_b600fe_idx"),
        ),
        migrations.AddIndex(
            model_name="synclog",
            index=models.Index(
                fields=["layer", "status"], name="geodata_syn_layer_i_6ab5a1_idx"
            ),
        ),
    ]
