# Generated by Django 4.2.7 on 2025-11-21 12:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GeneratedFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file_path",
                    models.CharField(
                        db_index=True,
                        help_text="Ruta completa del archivo",
                        max_length=500,
                        unique=True,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("export", "Export"),
                            ("report", "Report"),
                            ("analysis", "Analysis"),
                            ("monitoring", "Monitoring"),
                            ("temp", "Temporary"),
                            ("backup", "Backup"),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("generating", "Generating"),
                            ("ready", "Ready"),
                            ("downloading", "Downloading"),
                            ("expired", "Expired"),
                            ("error", "Error"),
                        ],
                        default="generating",
                        max_length=20,
                    ),
                ),
                (
                    "size",
                    models.BigIntegerField(default=0, help_text="Tamaño en bytes"),
                ),
                (
                    "hash_md5",
                    models.CharField(
                        blank=True, help_text="Hash MD5 del archivo", max_length=32
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "expires_at",
                    models.DateTimeField(
                        db_index=True, help_text="Fecha de expiración"
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("download_count", models.IntegerField(default=0)),
                ("last_accessed", models.DateTimeField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="generated_files",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Generated File",
                "verbose_name_plural": "Generated Files",
                "db_table": "core_generated_file",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["category", "status"],
                        name="core_genera_categor_394adf_idx",
                    ),
                    models.Index(
                        fields=["expires_at", "deleted_at"],
                        name="core_genera_expires_fcb96b_idx",
                    ),
                    models.Index(
                        fields=["user", "category"],
                        name="core_genera_user_id_9b1161_idx",
                    ),
                ],
            },
        ),
    ]
