# Generated by Django 4.2.7 on 2025-11-28 21:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "role_type",
                    models.CharField(
                        choices=[
                            ("super_admin", "Super Administrador"),
                            ("area_admin", "Administrador de Área"),
                            ("analyst_ai", "Analista IA"),
                            ("loader", "Cargador de Capas"),
                            ("monitor_analyst", "Analista de Monitoreo"),
                            ("viewer", "Visualizador"),
                            ("downloader", "Descargador"),
                            ("editor", "Editor"),
                            ("custom", "Rol Personalizado"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("can_upload_layers", models.BooleanField(default=False)),
                ("can_view_layers", models.BooleanField(default=True)),
                ("can_edit_layers", models.BooleanField(default=False)),
                ("can_delete_layers", models.BooleanField(default=False)),
                ("can_download_layers", models.BooleanField(default=False)),
                ("can_create_analysis", models.BooleanField(default=False)),
                ("can_view_analysis", models.BooleanField(default=True)),
                ("can_delete_analysis", models.BooleanField(default=False)),
                ("can_upload_agents", models.BooleanField(default=False)),
                ("can_create_monitors", models.BooleanField(default=False)),
                ("can_view_monitors", models.BooleanField(default=True)),
                ("can_configure_alerts", models.BooleanField(default=False)),
                ("can_manage_users", models.BooleanField(default=False)),
                ("can_approve_users", models.BooleanField(default=False)),
                ("can_create_areas", models.BooleanField(default=False)),
                ("can_share_resources", models.BooleanField(default=False)),
                ("can_export_reports", models.BooleanField(default=False)),
                ("can_view_audit_logs", models.BooleanField(default=False)),
                ("is_system_role", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Rol",
                "verbose_name_plural": "Roles",
                "db_table": "users_role",
            },
        ),
        migrations.AlterModelOptions(
            name="userprofile",
            options={
                "verbose_name": "Perfil de Usuario",
                "verbose_name_plural": "Perfiles de Usuario",
            },
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="api_key",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="last_login_ip",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="notification_settings",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="preferences",
        ),
        migrations.AddField(
            model_name="userprofile",
            name="access_justification",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="approval_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pendiente de Aprobación"),
                    ("approved", "Aprobado"),
                    ("rejected", "Rechazado"),
                    ("suspended", "Suspendido"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="approved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_users",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="userprofile",
            name="department",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="email_notifications",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="last_activity",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="notify_alerts_critical",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="notify_alerts_low",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="notify_alerts_medium",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="notify_analysis_complete",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="notify_analysis_failed",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="notify_resource_shared",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="notify_weekly_report",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="organization",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="phone",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="position",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="push_notifications",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="rejection_reason",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="sms_notifications",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="two_factor_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="two_factor_secret",
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterModelTable(
            name="userprofile",
            table="users_profile",
        ),
        migrations.CreateModel(
            name="Area",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "privacy",
                    models.CharField(
                        choices=[
                            ("private", "Privado"),
                            ("internal", "Interno"),
                            ("public", "Público"),
                        ],
                        default="private",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "admins",
                    models.ManyToManyField(
                        blank=True,
                        related_name="administered_areas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Área",
                "verbose_name_plural": "Áreas",
                "db_table": "users_area",
            },
        ),
        migrations.CreateModel(
            name="ActivityLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("login", "Inicio de Sesión"),
                            ("logout", "Cierre de Sesión"),
                            ("upload_layer", "Subir Capa"),
                            ("delete_layer", "Eliminar Capa"),
                            ("export_layer", "Exportar Capa"),
                            ("create_analysis", "Crear Análisis"),
                            ("delete_analysis", "Eliminar Análisis"),
                            ("create_monitor", "Crear Monitor"),
                            ("share_resource", "Compartir Recurso"),
                            ("edit_user", "Editar Usuario"),
                            ("approve_user", "Aprobar Usuario"),
                            ("reject_user", "Rechazar Usuario"),
                        ],
                        max_length=50,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activity_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Log de Actividad",
                "verbose_name_plural": "Logs de Actividad",
                "db_table": "users_activity_log",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="userprofile",
            name="area",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="members",
                to="users.area",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="role",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="users.role",
            ),
        ),
    ]
