# deployment/kubernetes/secrets.yaml
---
# SMGI Backend - Kubernetes Secrets
# Sistema de Monitoreo Geoespacial Inteligente
# Credenciales sensibles para el entorno de desarrollo local en Kubernetes
# 
# ⚠️ ADVERTENCIA ⚠️
# Este archivo contiene credenciales sensibles codificadas en base64.
# NO debe ser commiteado al repositorio público.
# En producción, usar un almacén seguro como HashiCorp Vault o AWS Secrets Manager.
# Para desarrollo local, asegurarse de que el archivo esté en .gitignore.

apiVersion: v1
kind: Secret
metadata:
  name: smgi-secrets
  namespace: smgi
  labels:
    app: smgi-backend
    component: secrets

# --- MEJORA: Tipo de secreto ---
# Opaque es el tipo por defecto para datos arbitrarios.
type: Opaque

# --- MEJORA: Datos sensibles codificados en base64 ---
# Estos valores deben ser codificados en base64 antes de ser colocados aquí.
# En bash: echo -n 'tu_valor' | base64
# En Python: import base64; base64.b64encode(b'tu_valor').decode()
data:
  # Django SECRET_KEY
  secret-key: "ZGphbmdvLWluc2VjdXJlLWRldmVsb3BtZW50LWtleS1jaGFuZ2UtbWUtaW4tcHJvZHVjdGlvbi0hISE=" # 'django-insecure-development-key-change-me-in-production-!!!'
  
  # Database password
  db-password: "c21naV9kZXZfcGFzc3dvcmQ=" # 'smgi_dev_password'
  
  # Redis password (si se usa autenticación)
  redis-password: "cmVkaXNfZGV2X3Bhc3N3b3Jk" # 'redis_dev_password'
  
  # Email credentials
  email-host-user: "bm9yZXBseUBpaWFwLm9yZy5jbw==" # 'noreply@iiap.org.co'
  email-host-password: "dGVzdC1lbWFpbC1wYXNzd29yZA==" # 'test-email-password'
  
  # Twilio credentials (si se usa para SMS)
  twilio-account-sid: "QUMxMjM0NTY3ODkwYWJjZGVmZ2hpams=" # 'AC1234567890abcdefg hijkl'
  twilio-auth-token: "YXV0aF90b2tlbl90ZXN0XzEyMzQ1Njc4OTA=" # 'auth_token_test_1234567890'
  
  # FCM server key (si se usa para notificaciones push)
  fcm-server-key: "ZmNtX3NlcnZlcl9rZXlfdGVzdF8xMjM0NTY3ODkw" # 'fcm_server_key_test_1234567890'
  
  # ArcGIS credentials (si se usa autenticación básica)
  arcgis-username: "YXJjZ2lzX2Rldl91c2Vy" # 'arcgis_dev_user'
  arcgis-password: "YXJjZ2lzX2Rldl9wYXNzd29yZA==" # 'arcgis_dev_password'
  
  # API key general
  api-key: "YXBpX2tleV90ZXN0XzEyMzQ1Njc4OTA=" # 'api_key_test_1234567890'

# --- MEJORA: StringData (opcional) ---
# stringData permite ingresar datos en texto plano y Kubernetes los codifica automáticamente.
# Útil para desarrollo o cuando se generan secretos dinámicamente.
# stringData:
#   secret-key: "django-insecure-development-key-change-me-in-production-!!!"
#   db-password: "smgi_dev_password"
#   redis-password: "redis_dev_password"
#   email-host-user: "noreply@iiap.org.co"
#   email-host-password: "test-email-password"
#   twilio-account-sid: "AC1234567890abcdefg hijkl"
#   twilio-auth-token: "auth_token_test_1234567890"
#   fcm-server-key: "fcm_server_key_test_1234567890"
#   arcgis-username: "arcgis_dev_user"
#   arcgis-password: "arcgis_dev_password"
#   api-key: "api_key_test_1234567890"
