# Generated by Django 4.2.7 on 2025-11-10 16:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("geodata", "0001_initial"),
        ("monitoring", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Workflow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="fecha de actualización"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="activo")),
                ("name", models.CharField(max_length=255, verbose_name="nombre")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="descripción"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Borrador"),
                            ("active", "Activo"),
                            ("paused", "Pausado"),
                            ("archived", "Archivado"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="estado",
                    ),
                ),
                (
                    "workflow_definition",
                    models.JSONField(
                        default=dict,
                        help_text="Definición del flujo de trabajo en formato JSON",
                        verbose_name="definición del workflow",
                    ),
                ),
                (
                    "trigger_type",
                    models.CharField(
                        choices=[
                            ("manual", "Manual"),
                            ("schedule", "Programado"),
                            ("detection", "Detección"),
                            ("webhook", "Webhook"),
                            ("data_change", "Cambio en Datos"),
                        ],
                        default="manual",
                        max_length=50,
                        verbose_name="tipo de activador",
                    ),
                ),
                (
                    "trigger_config",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        verbose_name="configuración del activador",
                    ),
                ),
                (
                    "timeout_minutes",
                    models.IntegerField(
                        default=60,
                        help_text="Tiempo máximo de ejecución",
                        verbose_name="tiempo de espera (minutos)",
                    ),
                ),
                (
                    "retry_count",
                    models.IntegerField(
                        default=0,
                        help_text="Número de reintentos en caso de fallo",
                        verbose_name="número de reintentos",
                    ),
                ),
                (
                    "execution_count",
                    models.IntegerField(
                        default=0, verbose_name="número de ejecuciones"
                    ),
                ),
                (
                    "success_count",
                    models.IntegerField(default=0, verbose_name="ejecuciones exitosas"),
                ),
                (
                    "failure_count",
                    models.IntegerField(default=0, verbose_name="ejecuciones fallidas"),
                ),
                (
                    "last_execution",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="última ejecución"
                    ),
                ),
                (
                    "tags",
                    models.JSONField(
                        blank=True, default=list, verbose_name="etiquetas"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="metadatos"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="creado por",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="actualizado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "workflow",
                "verbose_name_plural": "workflows",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WorkflowTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="fecha de actualización"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="activo")),
                ("name", models.CharField(max_length=255, verbose_name="nombre")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="descripción"),
                ),
                (
                    "task_type",
                    models.CharField(
                        choices=[
                            ("agent_execution", "Ejecución de Agente"),
                            ("data_sync", "Sincronización de Datos"),
                            ("monitor_check", "Verificación de Monitor"),
                            ("notification", "Notificación"),
                            ("data_transform", "Transformación de Datos"),
                            ("conditional", "Condicional"),
                            ("loop", "Bucle"),
                            ("api_call", "Llamada API"),
                            ("script", "Script"),
                        ],
                        max_length=30,
                        verbose_name="tipo de tarea",
                    ),
                ),
                (
                    "configuration",
                    models.JSONField(
                        default=dict,
                        help_text="Configuración específica de la tarea",
                        verbose_name="configuración",
                    ),
                ),
                (
                    "order",
                    models.IntegerField(
                        default=0,
                        help_text="Orden de ejecución en el workflow",
                        verbose_name="orden",
                    ),
                ),
                (
                    "timeout_minutes",
                    models.IntegerField(
                        default=30, verbose_name="tiempo de espera (minutos)"
                    ),
                ),
                (
                    "retry_on_failure",
                    models.BooleanField(
                        default=False, verbose_name="reintentar en caso de fallo"
                    ),
                ),
                (
                    "continue_on_failure",
                    models.BooleanField(
                        default=False, verbose_name="continuar en caso de fallo"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="creado por",
                    ),
                ),
                (
                    "depends_on",
                    models.ManyToManyField(
                        blank=True,
                        related_name="dependent_tasks",
                        to="automation.workflowtask",
                        verbose_name="depende de",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="actualizado por",
                    ),
                ),
                (
                    "workflow",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="automation.workflow",
                        verbose_name="workflow",
                    ),
                ),
            ],
            options={
                "verbose_name": "tarea de workflow",
                "verbose_name_plural": "tareas de workflow",
                "ordering": ["workflow", "order"],
                "unique_together": {("workflow", "order")},
            },
        ),
        migrations.CreateModel(
            name="WorkflowExecution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="fecha de actualización"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="activo")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendiente"),
                            ("running", "Ejecutando"),
                            ("success", "Exitoso"),
                            ("failed", "Fallido"),
                            ("cancelled", "Cancelado"),
                            ("timeout", "Tiempo Agotado"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="estado",
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="iniciado en"
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="completado en"
                    ),
                ),
                (
                    "input_data",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="datos de entrada"
                    ),
                ),
                (
                    "output_data",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="datos de salida"
                    ),
                ),
                (
                    "trigger_source",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="fuente de activación"
                    ),
                ),
                (
                    "trigger_data",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="datos de activación"
                    ),
                ),
                ("logs", models.TextField(blank=True, verbose_name="logs")),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="mensaje de error"),
                ),
                (
                    "tasks_total",
                    models.IntegerField(default=0, verbose_name="total de tareas"),
                ),
                (
                    "tasks_completed",
                    models.IntegerField(default=0, verbose_name="tareas completadas"),
                ),
                (
                    "tasks_failed",
                    models.IntegerField(default=0, verbose_name="tareas fallidas"),
                ),
                (
                    "task_id",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="ID de tarea"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="creado por",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="actualizado por",
                    ),
                ),
                (
                    "workflow",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="executions",
                        to="automation.workflow",
                        verbose_name="workflow",
                    ),
                ),
            ],
            options={
                "verbose_name": "ejecución de workflow",
                "verbose_name_plural": "ejecuciones de workflow",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TaskExecution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendiente"),
                            ("running", "Ejecutando"),
                            ("success", "Exitoso"),
                            ("failed", "Fallido"),
                            ("skipped", "Omitido"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="estado",
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="iniciado en"
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="completado en"
                    ),
                ),
                (
                    "input_data",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="datos de entrada"
                    ),
                ),
                (
                    "output_data",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="datos de salida"
                    ),
                ),
                ("logs", models.TextField(blank=True, verbose_name="logs")),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="mensaje de error"),
                ),
                (
                    "retry_count",
                    models.IntegerField(default=0, verbose_name="número de reintentos"),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="executions",
                        to="automation.workflowtask",
                        verbose_name="tarea",
                    ),
                ),
                (
                    "workflow_execution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="task_executions",
                        to="automation.workflowexecution",
                        verbose_name="ejecución de workflow",
                    ),
                ),
            ],
            options={
                "verbose_name": "ejecución de tarea",
                "verbose_name_plural": "ejecuciones de tareas",
                "ordering": ["workflow_execution", "task__order"],
            },
        ),
        migrations.CreateModel(
            name="AutomationRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="fecha de actualización"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="activo")),
                ("name", models.CharField(max_length=255, verbose_name="nombre")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="descripción"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Activo"), ("inactive", "Inactivo")],
                        default="active",
                        max_length=20,
                        verbose_name="estado",
                    ),
                ),
                (
                    "trigger_event",
                    models.CharField(
                        choices=[
                            ("detection_created", "Detección Creada"),
                            ("monitor_alert", "Alerta de Monitor"),
                            ("data_updated", "Datos Actualizados"),
                            ("schedule", "Programado"),
                            ("threshold_exceeded", "Umbral Excedido"),
                        ],
                        max_length=100,
                        verbose_name="evento activador",
                    ),
                ),
                (
                    "conditions",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Condiciones que deben cumplirse para activar",
                        verbose_name="condiciones",
                    ),
                ),
                (
                    "workflow_input",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Datos de entrada para el workflow",
                        verbose_name="entrada del workflow",
                    ),
                ),
                (
                    "throttle_minutes",
                    models.IntegerField(
                        default=0,
                        help_text="Minutos a esperar antes de activar nuevamente",
                        verbose_name="minutos de espera",
                    ),
                ),
                (
                    "trigger_count",
                    models.IntegerField(
                        default=0, verbose_name="número de activaciones"
                    ),
                ),
                (
                    "last_triggered",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="última activación"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="creado por",
                    ),
                ),
                (
                    "data_sources",
                    models.ManyToManyField(
                        blank=True,
                        related_name="automation_rules",
                        to="geodata.datasource",
                        verbose_name="fuentes de datos",
                    ),
                ),
                (
                    "monitors",
                    models.ManyToManyField(
                        blank=True,
                        related_name="automation_rules",
                        to="monitoring.monitor",
                        verbose_name="monitores",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="actualizado por",
                    ),
                ),
                (
                    "workflow",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="automation_rules",
                        to="automation.workflow",
                        verbose_name="workflow a ejecutar",
                    ),
                ),
            ],
            options={
                "verbose_name": "regla de automatización",
                "verbose_name_plural": "reglas de automatización",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="WorkflowSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="fecha de actualización"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="activo")),
                ("name", models.CharField(max_length=255, verbose_name="nombre")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="descripción"),
                ),
                (
                    "schedule_type",
                    models.CharField(
                        choices=[
                            ("interval", "Intervalo"),
                            ("cron", "Cron"),
                            ("once", "Una vez"),
                        ],
                        max_length=20,
                        verbose_name="tipo de programación",
                    ),
                ),
                (
                    "interval_minutes",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="intervalo (minutos)"
                    ),
                ),
                (
                    "cron_expression",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="expresión cron"
                    ),
                ),
                (
                    "scheduled_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="hora programada"
                    ),
                ),
                (
                    "input_data",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="datos de entrada"
                    ),
                ),
                (
                    "is_enabled",
                    models.BooleanField(default=True, verbose_name="habilitado"),
                ),
                (
                    "last_run",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="última ejecución"
                    ),
                ),
                (
                    "next_run",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="próxima ejecución"
                    ),
                ),
                (
                    "run_count",
                    models.IntegerField(
                        default=0, verbose_name="número de ejecuciones"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="creado por",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="actualizado por",
                    ),
                ),
                (
                    "workflow",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedules",
                        to="automation.workflow",
                        verbose_name="workflow",
                    ),
                ),
            ],
            options={
                "verbose_name": "programación de workflow",
                "verbose_name_plural": "programaciones de workflows",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["workflow", "is_enabled"],
                        name="automation__workflo_7d6248_idx",
                    ),
                    models.Index(
                        fields=["next_run", "is_enabled"],
                        name="automation__next_ru_9fc26f_idx",
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="workflowexecution",
            index=models.Index(
                fields=["workflow", "status"], name="automation__workflo_2bbb85_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="workflowexecution",
            index=models.Index(
                fields=["status", "created_at"], name="automation__status_9c4ce7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="workflowexecution",
            index=models.Index(
                fields=["task_id"], name="automation__task_id_c89adf_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="workflow",
            index=models.Index(
                fields=["status", "is_active"], name="automation__status_8bf75d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="workflow",
            index=models.Index(
                fields=["trigger_type"], name="automation__trigger_d739c5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="automationrule",
            index=models.Index(
                fields=["trigger_event", "status"],
                name="automation__trigger_c81211_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="automationrule",
            index=models.Index(
                fields=["status", "is_active"], name="automation__status_449293_idx"
            ),
        ),
    ]
