# Generated by Django 4.2.7 on 2025-11-10 16:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("geodata", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AgentCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="fecha de actualización"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="activo")),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="nombre"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="descripción"),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text="Nombre del icono (ej: map, chart, alert)",
                        max_length=50,
                        verbose_name="icono",
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        default="#3B82F6",
                        help_text="Color hexadecimal",
                        max_length=7,
                        verbose_name="color",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="creado por",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="actualizado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "categoría de agente",
                "verbose_name_plural": "categorías de agentes",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="AgentTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="fecha de actualización"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="activo")),
                ("name", models.CharField(max_length=255, verbose_name="nombre")),
                ("description", models.TextField(verbose_name="descripción")),
                (
                    "agent_type",
                    models.CharField(
                        choices=[
                            ("change_detection", "Detección de Cambios"),
                            ("classification", "Clasificación"),
                            ("segmentation", "Segmentación"),
                            ("prediction", "Predicción"),
                            ("statistics", "Estadísticas"),
                            ("custom", "Personalizado"),
                        ],
                        max_length=30,
                        verbose_name="tipo de agente",
                    ),
                ),
                (
                    "code_template",
                    models.TextField(
                        help_text="Código con placeholders para personalización",
                        verbose_name="plantilla de código",
                    ),
                ),
                (
                    "parameters_schema",
                    models.JSONField(
                        default=dict, verbose_name="esquema de parámetros"
                    ),
                ),
                (
                    "default_parameters",
                    models.JSONField(
                        default=dict, verbose_name="parámetros por defecto"
                    ),
                ),
                (
                    "tags",
                    models.JSONField(
                        blank=True, default=list, verbose_name="etiquetas"
                    ),
                ),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="agent_templates/",
                        verbose_name="miniatura",
                    ),
                ),
                (
                    "usage_count",
                    models.IntegerField(default=0, verbose_name="veces usado"),
                ),
                (
                    "is_featured",
                    models.BooleanField(default=False, verbose_name="destacado"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="templates",
                        to="agents.agentcategory",
                        verbose_name="categoría",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="creado por",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="actualizado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "plantilla de agente",
                "verbose_name_plural": "plantillas de agentes",
                "ordering": ["-usage_count", "name"],
            },
        ),
        migrations.CreateModel(
            name="Agent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="fecha de actualización"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="activo")),
                ("name", models.CharField(max_length=255, verbose_name="nombre")),
                ("description", models.TextField(verbose_name="descripción")),
                (
                    "agent_type",
                    models.CharField(
                        choices=[
                            ("change_detection", "Detección de Cambios"),
                            ("classification", "Clasificación"),
                            ("segmentation", "Segmentación"),
                            ("prediction", "Predicción"),
                            ("statistics", "Estadísticas"),
                            ("custom", "Personalizado"),
                        ],
                        max_length=30,
                        verbose_name="tipo de agente",
                    ),
                ),
                (
                    "version",
                    models.CharField(
                        default="1.0.0", max_length=20, verbose_name="versión"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Borrador"),
                            ("published", "Publicado"),
                            ("archived", "Archivado"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="estado",
                    ),
                ),
                (
                    "code",
                    models.TextField(
                        help_text="Código Python del agente", verbose_name="código"
                    ),
                ),
                (
                    "requirements",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Lista de paquetes Python requeridos",
                        verbose_name="dependencias",
                    ),
                ),
                (
                    "parameters_schema",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="JSON Schema para validar parámetros de entrada",
                        verbose_name="esquema de parámetros",
                    ),
                ),
                (
                    "default_parameters",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="parámetros por defecto"
                    ),
                ),
                (
                    "tags",
                    models.JSONField(
                        blank=True, default=list, verbose_name="etiquetas"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="metadatos"
                    ),
                ),
                (
                    "execution_count",
                    models.IntegerField(
                        default=0, verbose_name="número de ejecuciones"
                    ),
                ),
                (
                    "success_count",
                    models.IntegerField(default=0, verbose_name="ejecuciones exitosas"),
                ),
                (
                    "failure_count",
                    models.IntegerField(default=0, verbose_name="ejecuciones fallidas"),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        default=False,
                        help_text="Si es público, estará disponible en el marketplace",
                        verbose_name="público",
                    ),
                ),
                (
                    "is_verified",
                    models.BooleanField(
                        default=False,
                        help_text="Agentes verificados por el equipo de SMGI",
                        verbose_name="verificado",
                    ),
                ),
                ("downloads", models.IntegerField(default=0, verbose_name="descargas")),
                (
                    "rating",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=3,
                        verbose_name="calificación",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="agents",
                        to="agents.agentcategory",
                        verbose_name="categoría",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="creado por",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="actualizado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "agente",
                "verbose_name_plural": "agentes",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AgentSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="fecha de actualización"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="activo")),
                ("name", models.CharField(max_length=255, verbose_name="nombre")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="descripción"),
                ),
                (
                    "schedule_type",
                    models.CharField(
                        choices=[
                            ("interval", "Intervalo"),
                            ("cron", "Cron"),
                            ("once", "Una vez"),
                        ],
                        max_length=20,
                        verbose_name="tipo de programación",
                    ),
                ),
                (
                    "interval_minutes",
                    models.IntegerField(
                        blank=True,
                        help_text="Para tipo interval",
                        null=True,
                        verbose_name="intervalo (minutos)",
                    ),
                ),
                (
                    "cron_expression",
                    models.CharField(
                        blank=True,
                        help_text="Para tipo cron (ej: 0 0 * * *)",
                        max_length=100,
                        verbose_name="expresión cron",
                    ),
                ),
                (
                    "scheduled_time",
                    models.DateTimeField(
                        blank=True,
                        help_text="Para tipo once",
                        null=True,
                        verbose_name="hora programada",
                    ),
                ),
                (
                    "parameters",
                    models.JSONField(default=dict, verbose_name="parámetros"),
                ),
                (
                    "is_enabled",
                    models.BooleanField(default=True, verbose_name="habilitado"),
                ),
                (
                    "last_run",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="última ejecución"
                    ),
                ),
                (
                    "next_run",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="próxima ejecución"
                    ),
                ),
                (
                    "run_count",
                    models.IntegerField(
                        default=0, verbose_name="número de ejecuciones"
                    ),
                ),
                (
                    "agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedules",
                        to="agents.agent",
                        verbose_name="agente",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="creado por",
                    ),
                ),
                (
                    "input_datasets",
                    models.ManyToManyField(
                        blank=True,
                        related_name="agent_schedules",
                        to="geodata.dataset",
                        verbose_name="datasets de entrada",
                    ),
                ),
                (
                    "input_layers",
                    models.ManyToManyField(
                        blank=True,
                        related_name="agent_schedules",
                        to="geodata.layer",
                        verbose_name="capas de entrada",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="actualizado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "programación de agente",
                "verbose_name_plural": "programaciones de agentes",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["agent", "is_enabled"],
                        name="agents_agen_agent_i_aac254_idx",
                    ),
                    models.Index(
                        fields=["next_run", "is_enabled"],
                        name="agents_agen_next_ru_16ec0a_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="AgentRating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rating",
                    models.IntegerField(
                        choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)],
                        help_text="Calificación de 1 a 5 estrellas",
                        verbose_name="calificación",
                    ),
                ),
                ("comment", models.TextField(blank=True, verbose_name="comentario")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="fecha de actualización"
                    ),
                ),
                (
                    "agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ratings",
                        to="agents.agent",
                        verbose_name="agente",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agent_ratings",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "calificación de agente",
                "verbose_name_plural": "calificaciones de agentes",
                "ordering": ["-created_at"],
                "unique_together": {("agent", "user")},
            },
        ),
        migrations.CreateModel(
            name="AgentExecution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="fecha de actualización"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="activo")),
                (
                    "name",
                    models.CharField(blank=True, max_length=255, verbose_name="nombre"),
                ),
                (
                    "parameters",
                    models.JSONField(default=dict, verbose_name="parámetros"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendiente"),
                            ("running", "Ejecutando"),
                            ("success", "Exitoso"),
                            ("failed", "Fallido"),
                            ("cancelled", "Cancelado"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="estado",
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="iniciado en"
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="completado en"
                    ),
                ),
                (
                    "output_data",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="datos de salida"
                    ),
                ),
                (
                    "output_layers",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="IDs de capas generadas",
                        verbose_name="capas de salida",
                    ),
                ),
                ("logs", models.TextField(blank=True, verbose_name="logs")),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="mensaje de error"),
                ),
                (
                    "processing_time",
                    models.FloatField(
                        blank=True,
                        null=True,
                        verbose_name="tiempo de procesamiento (segundos)",
                    ),
                ),
                (
                    "memory_usage",
                    models.FloatField(
                        blank=True, null=True, verbose_name="uso de memoria (MB)"
                    ),
                ),
                (
                    "task_id",
                    models.CharField(
                        blank=True,
                        help_text="ID de la tarea Celery",
                        max_length=255,
                        verbose_name="ID de tarea",
                    ),
                ),
                (
                    "agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="executions",
                        to="agents.agent",
                        verbose_name="agente",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="creado por",
                    ),
                ),
                (
                    "input_datasets",
                    models.ManyToManyField(
                        blank=True,
                        related_name="agent_executions",
                        to="geodata.dataset",
                        verbose_name="datasets de entrada",
                    ),
                ),
                (
                    "input_layers",
                    models.ManyToManyField(
                        blank=True,
                        related_name="agent_executions",
                        to="geodata.layer",
                        verbose_name="capas de entrada",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="actualizado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "ejecución de agente",
                "verbose_name_plural": "ejecuciones de agentes",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["agent", "status"],
                        name="agents_agen_agent_i_325437_idx",
                    ),
                    models.Index(
                        fields=["status", "created_at"],
                        name="agents_agen_status_17d4e5_idx",
                    ),
                    models.Index(
                        fields=["task_id"], name="agents_agen_task_id_abce9c_idx"
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="agent",
            index=models.Index(
                fields=["agent_type", "status"], name="agents_agen_agent_t_394756_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="agent",
            index=models.Index(
                fields=["is_public", "is_verified"],
                name="agents_agen_is_publ_3c07af_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="agent",
            index=models.Index(
                fields=["-rating"], name="agents_agen_rating_64eee1_idx"
            ),
        ),
    ]
