# Generated by Django 4.2.7 on 2025-11-10 16:32

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("geodata", "0001_initial"),
        ("agents", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MonitoringProject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="fecha de actualización"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="activo")),
                ("name", models.CharField(max_length=255, verbose_name="nombre")),
                ("description", models.TextField(verbose_name="descripción")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Activo"),
                            ("paused", "Pausado"),
                            ("completed", "Completado"),
                            ("archived", "Archivado"),
                        ],
                        default="active",
                        max_length=20,
                        verbose_name="estado",
                    ),
                ),
                (
                    "area_of_interest",
                    django.contrib.gis.db.models.fields.PolygonField(
                        blank=True,
                        help_text="Polígono que define el área de monitoreo",
                        null=True,
                        srid=4326,
                        verbose_name="área de interés",
                    ),
                ),
                (
                    "configuration",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="configuración"
                    ),
                ),
                (
                    "tags",
                    models.JSONField(
                        blank=True, default=list, verbose_name="etiquetas"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="metadatos"
                    ),
                ),
                (
                    "start_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="fecha de inicio"
                    ),
                ),
                (
                    "end_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="fecha de fin"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="creado por",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="actualizado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "proyecto de monitoreo",
                "verbose_name_plural": "proyectos de monitoreo",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Monitor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="fecha de actualización"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="activo")),
                ("name", models.CharField(max_length=255, verbose_name="nombre")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="descripción"),
                ),
                (
                    "monitor_type",
                    models.CharField(
                        choices=[
                            ("change_detection", "Detección de Cambios"),
                            ("threshold", "Umbral"),
                            ("anomaly", "Anomalía"),
                            ("pattern", "Patrón"),
                            ("temporal", "Temporal"),
                            ("spatial", "Espacial"),
                            ("custom", "Personalizado"),
                        ],
                        max_length=30,
                        verbose_name="tipo de monitor",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Activo"),
                            ("paused", "Pausado"),
                            ("error", "Error"),
                            ("inactive", "Inactivo"),
                        ],
                        default="active",
                        max_length=20,
                        verbose_name="estado",
                    ),
                ),
                (
                    "parameters",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Parámetros para el análisis",
                        verbose_name="parámetros",
                    ),
                ),
                (
                    "check_interval",
                    models.IntegerField(
                        default=60,
                        help_text="Frecuencia de verificación",
                        verbose_name="intervalo de verificación (minutos)",
                    ),
                ),
                (
                    "last_check",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="última verificación"
                    ),
                ),
                (
                    "next_check",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="próxima verificación"
                    ),
                ),
                (
                    "check_count",
                    models.IntegerField(
                        default=0, verbose_name="número de verificaciones"
                    ),
                ),
                (
                    "detection_count",
                    models.IntegerField(
                        default=0, verbose_name="número de detecciones"
                    ),
                ),
                (
                    "tags",
                    models.JSONField(
                        blank=True, default=list, verbose_name="etiquetas"
                    ),
                ),
                (
                    "agent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="monitors",
                        to="agents.agent",
                        verbose_name="agente de análisis",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="creado por",
                    ),
                ),
                (
                    "data_sources",
                    models.ManyToManyField(
                        blank=True,
                        related_name="monitors",
                        to="geodata.datasource",
                        verbose_name="fuentes de datos",
                    ),
                ),
                (
                    "layers",
                    models.ManyToManyField(
                        blank=True,
                        related_name="monitors",
                        to="geodata.layer",
                        verbose_name="capas",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="monitors",
                        to="monitoring.monitoringproject",
                        verbose_name="proyecto",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="actualizado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "monitor",
                "verbose_name_plural": "monitores",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Detection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="fecha de actualización"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="activo")),
                ("title", models.CharField(max_length=255, verbose_name="título")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="descripción"),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("low", "Baja"),
                            ("medium", "Media"),
                            ("high", "Alta"),
                            ("critical", "Crítica"),
                        ],
                        default="medium",
                        max_length=20,
                        verbose_name="severidad",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "Nueva"),
                            ("confirmed", "Confirmada"),
                            ("false_positive", "Falso Positivo"),
                            ("resolved", "Resuelta"),
                            ("ignored", "Ignorada"),
                        ],
                        default="new",
                        max_length=20,
                        verbose_name="estado",
                    ),
                ),
                (
                    "detected_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="detectado en"
                    ),
                ),
                (
                    "location",
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True, null=True, srid=4326, verbose_name="ubicación"
                    ),
                ),
                (
                    "affected_area",
                    django.contrib.gis.db.models.fields.PolygonField(
                        blank=True, null=True, srid=4326, verbose_name="área afectada"
                    ),
                ),
                (
                    "analysis_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Resultados del análisis que generó la detección",
                        verbose_name="datos de análisis",
                    ),
                ),
                (
                    "confidence_score",
                    models.FloatField(
                        blank=True,
                        help_text="0.0 a 1.0",
                        null=True,
                        verbose_name="puntuación de confianza",
                    ),
                ),
                (
                    "evidence",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Evidencia de la detección (imágenes, datos, etc.)",
                        verbose_name="evidencia",
                    ),
                ),
                (
                    "reviewed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="revisado en"
                    ),
                ),
                (
                    "review_notes",
                    models.TextField(blank=True, verbose_name="notas de revisión"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="creado por",
                    ),
                ),
                (
                    "monitor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="detections",
                        to="monitoring.monitor",
                        verbose_name="monitor",
                    ),
                ),
                (
                    "related_layers",
                    models.ManyToManyField(
                        blank=True,
                        related_name="detections",
                        to="geodata.layer",
                        verbose_name="capas relacionadas",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_detections",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="revisado por",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="actualizado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "detección",
                "verbose_name_plural": "detecciones",
                "ordering": ["-detected_at"],
            },
        ),
        migrations.CreateModel(
            name="ChangeRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="fecha de actualización"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="activo")),
                (
                    "change_type",
                    models.CharField(
                        choices=[
                            ("added", "Añadido"),
                            ("removed", "Eliminado"),
                            ("modified", "Modificado"),
                            ("moved", "Movido"),
                        ],
                        max_length=20,
                        verbose_name="tipo de cambio",
                    ),
                ),
                (
                    "feature_id",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="ID de feature"
                    ),
                ),
                (
                    "before_geometry",
                    django.contrib.gis.db.models.fields.GeometryField(
                        blank=True,
                        null=True,
                        srid=4326,
                        verbose_name="geometría anterior",
                    ),
                ),
                (
                    "after_geometry",
                    django.contrib.gis.db.models.fields.GeometryField(
                        blank=True,
                        null=True,
                        srid=4326,
                        verbose_name="geometría posterior",
                    ),
                ),
                (
                    "before_attributes",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="atributos anteriores"
                    ),
                ),
                (
                    "after_attributes",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="atributos posteriores"
                    ),
                ),
                (
                    "change_magnitude",
                    models.FloatField(
                        blank=True,
                        help_text="Medida cuantitativa del cambio",
                        null=True,
                        verbose_name="magnitud del cambio",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="metadatos"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="creado por",
                    ),
                ),
                (
                    "detection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="changes",
                        to="monitoring.detection",
                        verbose_name="detección",
                    ),
                ),
                (
                    "layer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="change_records",
                        to="geodata.layer",
                        verbose_name="capa",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="actualizado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "registro de cambio",
                "verbose_name_plural": "registros de cambios",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Baseline",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="fecha de actualización"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="activo")),
                ("name", models.CharField(max_length=255, verbose_name="nombre")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="descripción"),
                ),
                (
                    "baseline_date",
                    models.DateTimeField(verbose_name="fecha de referencia"),
                ),
                (
                    "baseline_data",
                    models.JSONField(
                        default=dict,
                        help_text="Estado de referencia para comparación",
                        verbose_name="datos de referencia",
                    ),
                ),
                (
                    "feature_count",
                    models.IntegerField(default=0, verbose_name="número de features"),
                ),
                (
                    "area_coverage",
                    models.FloatField(
                        blank=True,
                        help_text="Área cubierta en km²",
                        null=True,
                        verbose_name="cobertura de área",
                    ),
                ),
                (
                    "is_current",
                    models.BooleanField(
                        default=True,
                        help_text="Si es la línea base actual para el monitor",
                        verbose_name="es actual",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="creado por",
                    ),
                ),
                (
                    "monitor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="baselines",
                        to="monitoring.monitor",
                        verbose_name="monitor",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="actualizado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "línea base",
                "verbose_name_plural": "líneas base",
                "ordering": ["-baseline_date"],
            },
        ),
        migrations.CreateModel(
            name="MonitoringReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="fecha de actualización"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="activo")),
                ("title", models.CharField(max_length=255, verbose_name="título")),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("daily", "Diario"),
                            ("weekly", "Semanal"),
                            ("monthly", "Mensual"),
                            ("custom", "Personalizado"),
                        ],
                        max_length=20,
                        verbose_name="tipo de reporte",
                    ),
                ),
                ("start_date", models.DateTimeField(verbose_name="fecha de inicio")),
                ("end_date", models.DateTimeField(verbose_name="fecha de fin")),
                ("summary", models.TextField(blank=True, verbose_name="resumen")),
                (
                    "statistics",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="estadísticas"
                    ),
                ),
                (
                    "detections_summary",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="resumen de detecciones"
                    ),
                ),
                (
                    "report_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="monitoring_reports/",
                        verbose_name="archivo de reporte",
                    ),
                ),
                (
                    "generated_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="generado en"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="creado por",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to="monitoring.monitoringproject",
                        verbose_name="proyecto",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="actualizado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "reporte de monitoreo",
                "verbose_name_plural": "reportes de monitoreo",
                "ordering": ["-generated_at"],
                "indexes": [
                    models.Index(
                        fields=["project", "report_type"],
                        name="monitoring__project_69beb5_idx",
                    ),
                    models.Index(
                        fields=["start_date", "end_date"],
                        name="monitoring__start_d_00a09b_idx",
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="monitoringproject",
            index=models.Index(
                fields=["status", "is_active"], name="monitoring__status_f75886_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="monitoringproject",
            index=models.Index(
                fields=["start_date", "end_date"], name="monitoring__start_d_3b99b5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="monitor",
            index=models.Index(
                fields=["project", "status"], name="monitoring__project_38ee45_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="monitor",
            index=models.Index(
                fields=["monitor_type", "is_active"],
                name="monitoring__monitor_53ed97_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="monitor",
            index=models.Index(
                fields=["next_check", "status"], name="monitoring__next_ch_05744c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="detection",
            index=models.Index(
                fields=["monitor", "status"], name="monitoring__monitor_9e257d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="detection",
            index=models.Index(
                fields=["severity", "status"], name="monitoring__severit_c392a2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="detection",
            index=models.Index(
                fields=["detected_at"], name="monitoring__detecte_c7aba8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="changerecord",
            index=models.Index(
                fields=["detection", "change_type"],
                name="monitoring__detecti_c5070e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="changerecord",
            index=models.Index(
                fields=["layer", "feature_id"], name="monitoring__layer_i_7eb399_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="baseline",
            index=models.Index(
                fields=["monitor", "is_current"], name="monitoring__monitor_6184fa_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="baseline",
            index=models.Index(
                fields=["baseline_date"], name="monitoring__baselin_28623f_idx"
            ),
        ),
    ]
