# Generated by Django 4.2.7 on 2025-11-30 23:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("info", "Información"),
                            ("success", "Éxito"),
                            ("warning", "Advertencia"),
                            ("error", "Error"),
                            ("alert", "Alerta"),
                        ],
                        default="info",
                        max_length=20,
                        verbose_name="tipo",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="título")),
                ("message", models.TextField(verbose_name="mensaje")),
                (
                    "related_object_type",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        verbose_name="tipo de objeto relacionado",
                    ),
                ),
                (
                    "related_object_id",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="ID de objeto relacionado"
                    ),
                ),
                ("is_read", models.BooleanField(default=False, verbose_name="leído")),
                (
                    "read_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="leído en"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="creado en"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "notificación",
                "verbose_name_plural": "notificaciones",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "is_read"],
                        name="notificatio_user_id_427e4b_idx",
                    ),
                    models.Index(
                        fields=["created_at"], name="notificatio_created_46ad24_idx"
                    ),
                ],
            },
        ),
    ]
